"""add subject type 2

Revision ID: 2dbf62881f01
Revises: da11094f8fd5
Create Date: 2025-11-26 20:13:01.552062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbf62881f01'
down_revision: Union[str, Sequence[str], None] = 'da11094f8fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_type', sa.Enum('EXAM', 'CREDIT', name='subjecttype'), server_default='CREDIT', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('subject_type')

    # ### end Alembic commands ###
