"""add subject type

Revision ID: da11094f8fd5
Revises: 661a73d6bb5d
Create Date: 2025-11-25 22:20:23.541817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da11094f8fd5'
down_revision: Union[str, Sequence[str], None] = '661a73d6bb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_title_user', ['title', 'user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint('uq_title_user', type_='unique')

    # ### end Alembic commands ###
